### ISSUE TITLE
confusion with two concepts

### ISSUE THREAD

**Issue by ZilinLu66** [DS4D-Group16/Assignment3#2]
In the handbook, Assignment 3 LO1:Data part shows some issues surrounding the data. I am a little bit confused with bias and underrepresentation. Can anyone explain what data bias means and give me a brief example? thx.

**Comment by HuiweiChen** [comment]
I have the same question. Maybe bias means what we learnt before, such as measuring error (omg it's error), system error, etc...? I don't know 555

**Comment by iWasOmen** [comment]
I think bias is that when we analyze something, we ignore some aspects, so it may lead to some errors. For example, we get the life progress in this project according to usage time but it's in fact affected by many aspects. So our conclusion may have bias. Underrepresentation is that we just use a small set of data to get a conclusion for a wider range situation. For example, if we use the data in Blackwood to give a conclusion for all nursing homes, it will result in underrepresentation.
