### ISSUE TITLE
Machinima

### ISSUE THREAD

**Issue by HuiweiChen** [DS4D-Group16/Assignment3#4]
[https://en.wikipedia.org/wiki/Machinima](url)
I just want to know, in the condition that we don't know machinima at all, how we chose to use this method to present accidentally? It's magic!

**Comment by ZilinLu66** [comment]
Sometimes we just come up with ideas based on personal experiences but maybe the ideas have their own terms in the related fields. It doesn't matter whether we are professionals or not. After all, the source of terms usually traces back to personal experiences.
