### ISSUE TITLE
Things that could improve our work?

### ISSUE THREAD

**Issue by UOEtuji** [DS4D-Group16/Assignment3#6]
When receiving the data set, if we have more personal information (such as age, medical report, disease, gender, etc.), will it affect the results of our current analysis (positive or negative impact?)? Or the data that we are using now, do we pay attention to information security issues? Such as encryption processing? User personal information protection, etc.?

**Comment by Yiting0802** [comment]
If we have more personal information, we can make more analysis on the relationship between the characteristics of occupants and their appliances usage pattern and can make more predictions towards occupants' habits and safety. Thus, more personal information will give us positive influence. 

The data we have got is only used in our analysis and we did not give it to another agency or upload it to an open website. However, we did not encrypt the data specifically, so there is a risk of data leakage.
